services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: transitor-tracker
      POSTGRES_USER: transitor-tracker
      POSTGRES_PASSWORD: password1
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/transitor-tracker -schemas=public -user=transitor-tracker -password=password1 -outOfOrder=true -connectRetries=5 migrate
    volumes:
      - ./database/migrations:/flyway/sql
    depends_on:
      - db
volumes:
  db:
