services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: transistor-tracker
      POSTGRES_USER: transistor-tracker
      POSTGRES_PASSWORD: password1
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/transistor-tracker -schemas=public -user=transistor-tracker -password=password1 -outOfOrder=true -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
volumes:
  db:
